name: ${project.artifactId}
main: me.grumpyrice.HeadShopPlugin
version: ${project.version}
authors: [GrumpyRice]
description: Purchase player heads!
depend: [Vault]
commands:
  headshop:
    description: Base command.
    usage: /<command>
    permission: headshop.use

permissions:
  headshop.*:
    description: Access to all of HeadShop features.
    children:
      headshop.use: true
      headshop.reload: true

  headshop.use:
    description: Access to HeadShopPlugin command - purchasing only.
    default: true

  headshops.reload:
    description: Access to HeadShopPlugin command - purchasing and reload.
    default: op